# Generated by Django 4.1.12 on 2023-10-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_user_contact_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
